apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golgana-prod

resources:
  - ../../base
  - pv.yaml

nameSuffix: -prod 

namespace: golgana-prod

patches:
  - path: patch-images.yaml
  - path: patch-ingress.yaml
