apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golgana-dev

resources:
  - ../../base
  - pv.yaml

patches:
  - path: patch-images.yaml
  - path: patch-ingress.yaml
