apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mysql-deployment.yaml
  - mysql-pvc.yaml
  - mysql-pv.yaml
  - ingress.yaml
  - init-sql-configmap.yaml
  - service-bd.yaml
